export const SET_NAVBAR_ACTIVEITEM = 'SET_NAVBAR_ACTIVEITEM';
export const BEGIN_LOGIN_REQUEST = 'SBEGIN_LOGIN_REQUEST';
export const SUCCESS_LOGIN_REQUEST = 'SUCCESS_LOGIN_REQUEST';
export const FAIL_LOGIN_REQUEST = 'FAIL_LOGIN_REQUEST';